const assert=require('node:assert/strict'),{render,grid}=require('../particles.js');
const w=120,h=80,data=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++)data.set(x<60?[180,40,40,255]:[40,80,190,255],(y*w+x)*4);
const opts={shape:'circle',density:20,size:85,emission:100,glow:0,spread:20,jitter:0,background:'black',blend:'light'};
const circle=render(data,w,h,opts);const sample=(r,x,y,c)=>r.data[(y*w+x)*4+c];assert.ok(sample(circle,15,15,0)>sample(circle,15,15,2),'Left red stays left');assert.ok(sample(circle,105,15,2)>sample(circle,105,15,0),'Right blue stays right');
for(const shape of ['square','diamond','hex','ring','grain','rgbdot','rgbstripe']){const r=render(data,w,h,{...opts,shape});assert.equal(r.data.length,data.length);assert.equal(r.points,circle.points);assert.equal(r.elements,shape.startsWith('rgb')?r.points*3:r.points);assert.notDeepEqual(r.data,circle.data,'Shape changes visible geometry');for(let i=3;i<r.data.length;i+=4)assert.equal(r.data[i],255);}
assert.ok(render(data,w,h,{...opts,density:40}).points>circle.points,'Density increases count');assert.equal(render(data,w,h,{...opts,size:160,glow:80}).points,circle.points,'Size/glow do not change particle count');
const small=render(data,w,h,{...opts,size:30}),large=render(data,w,h,{...opts,size:120});assert.ok(large.data.reduce((a,v,i)=>a+(i%4!==3?v:0),0)>small.data.reduce((a,v,i)=>a+(i%4!==3?v:0),0),'Size changes coverage');
const dark=render(data,w,h,{...opts,emission:0,background:'paper',blend:'ink'});for(let i=0;i<dark.data.length;i+=4)assert.deepEqual(Array.from(dark.data.slice(i,i+3)),[230,218,196]);
assert.notDeepEqual(render(data,w,h,{...opts,glow:70}).data,circle.data,'Glow extends emitted light');assert.deepEqual(render(data,w,h,{...opts,shape:'grain',jitter:80}).data,render(data,w,h,{...opts,shape:'grain',jitter:80}).data,'Irregular particles deterministic');
assert.deepEqual(grid(4000,4000,400),{cols:400,rows:400});assert.deepEqual(grid(4000,2000,400),{cols:400,rows:200});assert.ok(grid(20,10,400).cols<=20,'No empty oversampled grid on tiny photos');
const full=new Uint8ClampedArray(1024*1024*4);for(let i=0;i<full.length;i+=4)full.set([160,110,90,255],i);const t=performance.now();render(full,1024,1024,{...opts,shape:'rgbdot',density:400,glow:35});console.log('PASS: 8 shapes, photo coordinates, independent density/size/glow, RGB counts, backgrounds, deterministic grain, tiny input; 1MP / 480k RGB elements '+Math.round(performance.now()-t)+'ms');
