const $=id=>document.getElementById(id),view=$('view'),ctx=view.getContext('2d'),source=document.createElement('canvas'),sc=source.getContext('2d',{willReadFrequently:true}),mask=document.createElement('canvas'),mc=mask.getContext('2d',{willReadFrequently:true});
let donorPalette=null,donorSeq=0;
let pixels,img,colorMap,rawColorMap,strokes=[],activeStroke=null,tool='view',brushColor='#a9c5d3',compare=false,preset='sea',pending=false,loadSeq=0;
const defaults={color:85,auto:90,softness:30,paper:65,grain:0,pooling:30,threshold:18,aging:0,edges:0},values={...defaults};
const controls=[['color','彩色の濃さ'],['auto','自動彩色の量'],['threshold','淡い元色を除く'],['softness','色のにじみ'],['pooling','塗りむら'],['paper','紙の温かみ'],['grain','粒子を足す'],['aging','紙の擦れ'],['edges','縁の傷み']];
for(const [id,name] of controls){const label=document.createElement('label');label.className='range';label.innerHTML=`${name}<output id="${id}Out">${values[id]}</output><input id="${id}" type="range" min="0" max="100" value="${values[id]}">`;$('sliders').append(label);$(id).oninput=()=>{values[id]=+$(id).value;$(id+'Out').value=values[id];if(id==='softness'&&pixels)colorMap=TintEngine.extract(pixels.data,view.width,view.height,values.softness);schedule();};}
for(const [color,name] of [['#a9c5d3','淡い水色'],['#d3aaa4','薄紅'],['#bcb0cc','藤色'],['#b2bca2','枯れ緑'],['#d5bd99','砂色'],['#b8bfc1','銀灰']]){const b=document.createElement('button');b.style.background=color;b.title=name;b.setAttribute('aria-label',name);if(color===brushColor)b.classList.add('selected');b.onclick=()=>{brushColor=color;document.querySelectorAll('.swatches button').forEach(x=>x.classList.toggle('selected',x===b));setTool('paint');};$('swatches').append(b);}
function status(s){$('status').textContent=s;}
function schedule(){if(!pending){pending=true;requestAnimationFrame(()=>{pending=false;draw();});}}
function draw(){if(!pixels)return;if(compare){ctx.putImageData(pixels,0,0);return;}const particle=$('displayMode').value==='particles';const base=particle&&$('particleColor').value==='original'?pixels.data:TintEngine.render(pixels.data,view.width,view.height,renderOptions(),mc.getImageData(0,0,mask.width,mask.height).data,$('colorMode').value==='pigment'?rawColorMap:colorMap);let result=base;if(particle){const p=ParticleEngine.render(base,view.width,view.height,particleOptions());result=p.data;$('particleCount').textContent=p.points.toLocaleString()+'配置点 / '+p.elements.toLocaleString()+'粒（'+p.cols+' × '+p.rows+'）';}ctx.putImageData(new ImageData(new Uint8ClampedArray(result),view.width,view.height),0,0);}
function paintStroke(c,s,w,h){c.save();c.globalCompositeOperation='source-over';c.lineCap='round';c.lineJoin='round';c.strokeStyle=s.color;c.fillStyle=s.color;c.globalAlpha=.42;const r=s.size*Math.min(w,h)/100;for(const p of s.points){const g=c.createRadialGradient(p[0]*w,p[1]*h,0,p[0]*w,p[1]*h,r/2);g.addColorStop(0,s.color);g.addColorStop(.4,s.color);g.addColorStop(1,s.color+'00');c.fillStyle=g;c.beginPath();c.arc(p[0]*w,p[1]*h,r/2,0,Math.PI*2);c.fill();}c.restore();}
function rebuild(){mc.clearRect(0,0,mask.width,mask.height);for(const s of strokes)paintStroke(mc,s,mask.width,mask.height);schedule();}
function setTool(t){tool=t;if(t!=='view'&&$('displayMode').value==='particles')$('particleColor').value='tinted';if(compare)toggleCompare();document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===t));$('modeLabel').textContent=t==='view'?'透ける色と、残る影。':t==='paint'?'写真をなぞって、色を置く。':'写真をなぞって、色を抜く。';view.style.touchAction=t==='view'?'auto':'none';view.style.cursor=t==='view'?'default':'crosshair';document.querySelector('.studio').classList.toggle('editing',t!=='view');}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{preset=b.dataset.preset;$('useDonor').checked=false;if($('displayMode').value==='particles')$('particleColor').value='tinted';document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('selected',x===b));schedule();});
$('brush').oninput=()=>{$('brushOut').value=$('brush').value;};
function point(e){const r=view.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
view.onpointerdown=e=>{if(tool==='view'||!pixels)return;e.preventDefault();view.setPointerCapture(e.pointerId);activeStroke={color:tool==='erase'?'#808080':brushColor,size:+$('brush').value,points:[point(e)]};strokes.push(activeStroke);paintStroke(mc,activeStroke,mask.width,mask.height);schedule();};
view.onpointermove=e=>{if(!activeStroke)return;e.preventDefault();const p=point(e),prev=activeStroke.points.at(-1),d=Math.hypot(p[0]-prev[0],p[1]-prev[1]),n=Math.max(1,Math.ceil(d/(activeStroke.size/100*.16)));const added=[];for(let k=1;k<=n;k++)added.push([prev[0]+(p[0]-prev[0])*k/n,prev[1]+(p[1]-prev[1])*k/n]);activeStroke.points.push(...added);paintStroke(mc,{...activeStroke,points:added},mask.width,mask.height);schedule();};
function endStroke(){activeStroke=null;}$('undo').onclick=()=>{strokes.pop();rebuild();};view.onpointerup=endStroke;view.onpointercancel=endStroke;
function toggleCompare(){compare=!compare;$('compare').setAttribute('aria-pressed',compare);$('compare').textContent=compare?'彩色に戻る':'原画と比較';draw();}$('compare').onclick=toggleCompare;
async function openImage(url,name){const seq=++loadSeq;status('写真を読み込んでいます…');const candidate=new Image();candidate.decoding='async';try{candidate.src=url;await candidate.decode();if(seq!==loadSeq)return;img=candidate;const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight));source.width=view.width=mask.width=Math.round(img.naturalWidth*scale);source.height=view.height=mask.height=Math.round(img.naturalHeight*scale);sc.drawImage(img,0,0,source.width,source.height);pixels=sc.getImageData(0,0,source.width,source.height);colorMap=TintEngine.extract(pixels.data,source.width,source.height,values.softness);rawColorMap=TintEngine.extract(pixels.data,source.width,source.height,0);updateExtraction();strokes=[];mc.clearRect(0,0,mask.width,mask.height);compare=false;$('compare').textContent='原画と比較';$('compare').setAttribute('aria-pressed','false');$('empty').hidden=true;view.style.display='block';$('filename').textContent=name;$('dimensions').textContent=`${img.naturalWidth} × ${img.naturalHeight} / 端末内で加工`;$('save').disabled=$('share').disabled=false;setTool('view');draw();status($('colorMode').value==='pigment'?(colorMap.chroma<4?'元の色がないモノクロ写真です。紙の色だけを加えます。カラー原画を選ぶと顔料に塗り直せます。':'元の色を6色の顔料にまとめ、モノクロの土台に重ねました。'):colorMap.chroma<4?'元写真はほぼモノクロです。元の色を使う方式では彩色を控えます。「明暗から彩色」や筆で色を加えられます。':'元の色を抽出しました。淡い色へ変換し、陰影と粒子の上に重ねています。');}catch(e){status('この画像を読み込めませんでした。写真アプリからJPEGまたはPNGに書き出して、もう一度選んでください。');}finally{if(url.startsWith('blob:'))URL.revokeObjectURL(url);}}
function pick(e){const f=e.target.files[0];if(f)openImage(URL.createObjectURL(f),f.name);e.target.value='';}$('file').onchange=$('file2').onchange=pick;
$('demo').onclick=()=>openImage('sample-color.jpg','添付3 / カラー原画');
$('mat').ondragover=e=>e.preventDefault();$('mat').ondrop=e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)openImage(URL.createObjectURL(f),f.name);};
$('reset').onclick=()=>{Object.assign(values,defaults);Object.assign(particleValues,particleDefaults);syncParticleSliders();for(const [id]of controls){$(id).value=values[id];$(id+'Out').value=values[id];}strokes=[];preset='sea';$('useDonor').checked=false;document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',b.dataset.preset===preset));if(pixels){colorMap=TintEngine.extract(pixels.data,view.width,view.height,values.softness);rawColorMap=TintEngine.extract(pixels.data,view.width,view.height,0);}$('colorMode').value='pigment';$('particleShape').value='circle';$('particleBackground').value='black';$('particleBlend').value='light';$('particleColor').value='original';updateExtraction();updateParticleUI();rebuild();};
async function exportBlob(){if(!img)return;endStroke();status('彩色写真を書き出しています…');await new Promise(r=>setTimeout(r,30));const limit=Math.min(+$('resolution').value,$('displayMode').value==='particles'?2048:4096),scale=Math.min(1,limit/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.round(img.naturalWidth*scale),h=Math.round(img.naturalHeight*scale),out=document.createElement('canvas'),oc=out.getContext('2d'),m=document.createElement('canvas');out.width=m.width=w;out.height=m.height=h;oc.drawImage(img,0,0,w,h);const c=m.getContext('2d');for(const s of strokes)paintStroke(c,s,w,h);const p=oc.getImageData(0,0,w,h);const particle=$('displayMode').value==='particles';let result=particle&&$('particleColor').value==='original'?p.data:TintEngine.render(p.data,w,h,renderOptions(),c.getImageData(0,0,w,h).data,$('colorMode').value==='pigment'?rawColorMap:colorMap);if(particle)result=ParticleEngine.render(result,w,h,particleOptions()).data;oc.putImageData(new ImageData(new Uint8ClampedArray(result),w,h),0,0);return new Promise((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('書き出し失敗')),'image/png'));}
let savedUrl;
function showSave(blob){if(savedUrl)URL.revokeObjectURL(savedUrl);savedUrl=URL.createObjectURL(blob);$('savedImage').src=$('download').href=savedUrl;$('saved').showModal();status('書き出し完了。画像の長押し、またはPNGのダウンロードで保存できます。');}
let busy=false;async function save(share){if(busy||!img)return;busy=true;$('save').disabled=$('share').disabled=true;try{const blob=await exportBlob(),f=new File([blob],'yokohama-shashin.png',{type:'image/png'});if(share&&navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],title:'横濱寫眞'});status('共有が完了しました。');}catch(e){if(e.name==='AbortError'){status('共有を取り消しました。');}else showSave(blob);}}else showSave(blob);}catch(e){status('保存に失敗しました。保存サイズを小さくして再度お試しください。');}finally{busy=false;$('save').disabled=$('share').disabled=false;}}
$('save').onclick=()=>save(false);$('share').onclick=()=>save(true);$('close').onclick=()=>$('saved').close();

$('colorMode').onchange=()=>{if($('colorMode').value!=='pigment'){$('useDonor').checked=false;updatePaletteChoice();}updateExtraction();schedule();};
function updateModeControls(){$('useDonor').disabled=!donorPalette;const mode=$('colorMode').value;for(const id of ['threshold','pooling','aging','edges']){$(id).disabled=['threshold','pooling'].includes(id)?mode!=='pigment':mode!=='reference';$(id).parentElement.style.opacity=$(id).disabled?'.4':'1';}}
function updateExtraction(){updateModeControls();if(!colorMap)return;$('extraction').textContent=$('colorMode').value==='pigment'?(colorMap.chroma<4?'この写真には元の色がほぼありません。自動では紙の色だけが乗ります。カラー原画か彩色筆をお使いください。':'元の色を6色の顔料にまとめます。灰色・黒は無彩色のまま、紙の色だけを重ねます。'):$('colorMode').value==='reference'?'旧方式：明暗から青灰色も補います。肌や髪に青が乗る場合があります。':$('colorMode').value==='tonal'?'明暗に沿って、選んだ色調を重ねます。':colorMap.chroma<4?'元の色がほぼありません。筆、または明暗からの彩色をご利用ください。':'元写真の色を抽出 → 淡い顔料色に変換 → 同じ位置に重ねる';}
updateModeControls();

function renderOptions(){return {...values,preset,mode:$('colorMode').value,customPalette:$('colorMode').value==='pigment'&&$('useDonor').checked&&donorPalette?donorPalette.colors:null};}
function updatePaletteChoice(){const using=$('useDonor').checked&&donorPalette;document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',!using&&b.dataset.preset===preset));if(using){$('colorMode').value='pigment';$('particleColor').value='tinted';}updateExtraction();schedule();}
$('useDonor').onchange=updatePaletteChoice;
$('donorFile').onchange=async e=>{
 const f=e.target.files[0];e.target.value='';if(!f)return;const seq=++donorSeq,url=URL.createObjectURL(f),candidate=new Image();$('donorStatus').textContent='写真Aから色を取り出しています…';
 try{
  candidate.src=url;await candidate.decode();if(seq!==donorSeq)return;
  const scale=Math.min(1,512/Math.max(candidate.naturalWidth,candidate.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(candidate.naturalWidth*scale));c.height=Math.max(1,Math.round(candidate.naturalHeight*scale));const dc=c.getContext('2d');dc.drawImage(candidate,0,0,c.width,c.height);
  const extracted=TintEngine.extractPalette(dc.getImageData(0,0,c.width,c.height).data,c.width,c.height);
  if(!extracted.counts.some(n=>n>0)){$('donorStatus').textContent='写真Aには抽出できる色がほぼありません。カラー写真を選んでください。以前のパレットは保持しています。';return;}
  donorPalette=extracted;$('donorThumb').src=c.toDataURL('image/jpeg',.7);$('donorThumb').hidden=false;$('donorName').textContent=f.name;$('donorColors').replaceChildren();
  extracted.colors.forEach((color,i)=>{const item=document.createElement('span'),chip=document.createElement('i'),label=document.createElement('small');chip.style.background='rgb('+color.join(',')+')';label.textContent=extracted.labels[i];item.title=extracted.counts[i]?extracted.labels[i]+'：Aから抽出した淡色':extracted.labels[i]+'：Aでは未検出';if(!extracted.counts[i]){chip.className='missing';label.textContent+=' ×';}item.append(chip,label);$('donorColors').append(item);});
  $('useDonor').disabled=false;$('useDonor').checked=true;if(compare)toggleCompare();updatePaletteChoice();
  const missing=extracted.labels.filter((_,i)=>!extracted.counts[i]);$('donorStatus').textContent='Aの淡色をBの同じ色系統へ重ねます。'+(missing.length?'未検出：'+missing.join('・')+'。これらは自動彩色を控えます。':'');
 }catch(err){if(seq===donorSeq)$('donorStatus').textContent='写真Aを読み込めませんでした。JPEGまたはPNGで再度お試しください。';}
 finally{URL.revokeObjectURL(url);}
};

const particleDefaults={density:120,size:85,emission:100,glow:20,spread:20,jitter:0},particleValues={...particleDefaults};
const particleControls=[['density','密度 / 長辺の配置点',12,400],['size','粒の大きさ / 間隔に対する割合',10,180],['emission','発光・発色の強さ',0,200],['glow','光のにじみ',0,100],['spread','光の広がり',1,100],['jitter','位置のゆらぎ',0,100]];
for(const [key,label,min,max] of particleControls){const el=document.createElement('label');el.className='range';el.innerHTML=label+'<output id="p-'+key+'Out">'+particleValues[key]+'</output><input id="p-'+key+'" type="range" min="'+min+'" max="'+max+'" value="'+particleValues[key]+'">';$('particleSliders').append(el);$('p-'+key).oninput=()=>{particleValues[key]=+$('p-'+key).value;$('p-'+key+'Out').value=particleValues[key];schedule();};}
function particleOptions(){return {...particleValues,shape:$('particleShape').value,background:$('particleBackground').value,blend:$('particleBlend').value};}
function syncParticleSliders(){for(const [key]of particleControls){$('p-'+key).value=particleValues[key];$('p-'+key+'Out').value=particleValues[key];}}
function updateParticleUI(){const enabled=$('displayMode').value==='particles';document.querySelector('.studio').classList.toggle('particle-studio',enabled);for(const [key]of particleControls)$('p-'+key).disabled=!enabled;for(const id of ['particleColor','particleShape','particleBackground','particleBlend'])$(id).disabled=!enabled;document.querySelectorAll('[data-particle]').forEach(b=>b.disabled=!enabled);$('resolution').querySelector('[value="4096"]').disabled=enabled;if(enabled&&$('resolution').value==='4096')$('resolution').value='2048';if(!enabled)$('particleCount').textContent='写真のまま表示しています。';if(compare)toggleCompare();else schedule();}
for(const id of ['displayMode','particleColor','particleShape','particleBlend'])$(id).onchange=updateParticleUI;
$('particleBackground').onchange=()=>{$('particleBlend').value=$('particleBackground').value==='black'?'light':'ink';updateParticleUI();};
const particleRecipes={dots:{shape:'circle',density:100,size:80,emission:100,glow:15,spread:15,jitter:0,background:'black',blend:'light'},mosaic:{shape:'square',density:100,size:105,emission:100,glow:0,spread:20,jitter:0,background:'black',blend:'ink'},grain:{shape:'grain',density:180,size:100,emission:100,glow:0,spread:20,jitter:80,background:'paper',blend:'ink'},crt:{shape:'rgbdot',density:100,size:110,emission:100,glow:35,spread:15,jitter:0,background:'black',blend:'light'},stripes:{shape:'rgbstripe',density:100,size:100,emission:100,glow:25,spread:12,jitter:0,background:'black',blend:'light'}};
document.querySelectorAll('[data-particle]').forEach(b=>b.onclick=()=>{const r=particleRecipes[b.dataset.particle];Object.assign(particleValues,r);$('particleShape').value=r.shape;$('particleBackground').value=r.background;$('particleBlend').value=r.blend;syncParticleSliders();updateParticleUI();});
updateParticleUI();
